# Generated by Django 5.1.7 on 2025-03-29 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a musician name', max_length=64)),
                ('password', models.CharField(default='', help_text='Enter a password', max_length=64)),
                ('genre', models.CharField(default='', help_text='Enter a genre', max_length=64)),
                ('description', models.TextField(blank=True, help_text='Enter a description', null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a music name', max_length=64)),
                ('album', models.CharField(blank=True, help_text='Enter a album name', max_length=64, null=True)),
                ('genre', models.CharField(blank=True, help_text='Enter a genre', max_length=64, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('artist', models.ManyToManyField(blank=True, to='core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter a username', max_length=128)),
                ('password', models.CharField(help_text='Enter a password', max_length=64)),
                ('email', models.EmailField(help_text='Enter an email address', max_length=128)),
                ('age', models.IntegerField(default=0, help_text='Enter an age')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('followings', models.ManyToManyField(blank=True, to='core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a playlist name', max_length=64)),
                ('description', models.TextField(blank=True, help_text='Enter a description', null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.music')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playlist')),
            ],
            options={
                'unique_together': {('playlist', 'music')},
            },
        ),
    ]
